# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.14.2'

default_platform :ios

platform :ios do
  before_all do
   cocoapods
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  lane :beta do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number
    increment_build_number
    # Manage code signing
    match(type: 'development')
    # Build your app - more options available
    gym(scheme: 'JustForYou')
    # Upload to Crashlytics
    crashlytics
  end

  desc 'Deploy a new version to the App Store'
  lane :appstore do
    # match(type: 'appstore')
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

 # after_all do |lane|
  #  build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
   # sh 'git add -A'
   # sh "git commit -m \"Bulid \##{build_number}\""
 # end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
