fastlane_version '1.107.0'

default_platform :ios

platform :ios do
  before_all do
   # eure_git_status_clean
   # cocoapods
   # increment_build_number
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  lane :beta do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    increment_build_number
    # sigh(development: true, output_path: '/tmp')
    gym(scheme: 'JustForYou', use_legacy_build_api: true)
    crashlytics
  end

  desc 'Deploy a new version to the App Store'
  lane :appstore do
    # match(type: 'appstore')
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

 # after_all do |lane|
  #  build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
   # sh 'git add -A'
   # sh "git commit -m \"Bulid \##{build_number}\""
 # end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
