#scheme «JustForYou»

devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])


#launch_arguments(["-username Anton»])

# The directory in which the screenshots should be stored
output_directory './screenshots'

clear_previous_screenshots true

#add_photos ["MyTestApp/Assets/demo.jpg"]